import type { Product, Category } from '@/types'

export const DUMMY_CATEGORIES: Category[] = [
  {
    id: 'cat-1',
    name: 'Footwear',
    slug: 'footwear',
    image: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?q=80&w=800&auto=format&fit=crop',
    description: 'Step into style',
    count: 12,
  },
  {
    id: 'cat-2',
    name: 'Kids Clothing',
    slug: 'kids-clothing',
    image: 'https://images.unsplash.com/photo-1618354691373-d851c5c3a990?q=80&w=800&auto=format&fit=crop',
    description: 'Elevate your wardrobe',
    count: 18,
  },
  {
    id: 'cat-3',
    name: 'Electronics',
    slug: 'electronics',
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?q=80&w=800&auto=format&fit=crop',
    description: 'Tech for every need',
    count: 6,
  },
]

export const DUMMY_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    name: 'Classic Runner Sneakers',
    slug: 'classic-runner-sneakers',
    price: 89.99,
    description: 'Step into comfort and style with our classic runner sneakers. Lightweight design meets premium durable materials, featuring a breathable upper mesh and cushioned midsole designed by Aurexiva.',
    image: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?q=80&w=800&auto=format&fit=crop',
    category: 'Footwear',
    inStock: true,
    rating: 4.6,
    reviewsCount: 128,
    isFeatured: true,
  },
  {
    id: 'prod-2',
    name: 'Essential Hoodie',
    slug: 'essential-hoodie',
    price: 49.99,
    description: 'An everyday essential. Crafted from double-brushed organic cotton and recycled polyester for exceptional warmth, durability, and standard relaxed comfort by Aurexiva.',
    image: 'https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?q=80&w=800&auto=format&fit=crop',
    category: 'Kids Clothing',
    inStock: true,
    rating: 4.7,
    reviewsCount: 96,
    isFeatured: true,
  },
  {
    id: 'prod-3',
    name: 'Smart Watch Series 8',
    slug: 'smart-watch-series-8',
    price: 199.99,
    description: 'Advanced health sensors, crystal-clear Retina display, and refined watch design. Stay connected, monitor your workouts, and track sleep with Aurexiva Series 8.',
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?q=80&w=800&auto=format&fit=crop',
    category: 'Electronics',
    inStock: true,
    rating: 4.5,
    reviewsCount: 210,
    isFeatured: true,
  },
  {
    id: 'prod-4',
    name: 'Urban Backpack',
    slug: 'urban-backpack',
    price: 59.99,
    description: 'Water-resistant premium fabric, dedicated padded laptop sleeve, and ergonomic shoulder straps. Built for daily commutes and weekend travels, refined by Aurexiva.',
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?q=80&w=800&auto=format&fit=crop',
    category: 'Kids Clothing',
    inStock: true,
    rating: 4.6,
    reviewsCount: 78,
    isFeatured: true,
  },
  {
    id: 'prod-5',
    name: 'Digital Camera Pro',
    slug: 'digital-camera-pro',
    price: 399.99,
    description: 'Uncompromising image quality. Features a 24.2 MP full-frame sensor, ultra-fast autofocus tracking, and 4K video recording capabilities in a compact body, engineered by Aurexiva.',
    image: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?q=80&w=800&auto=format&fit=crop',
    category: 'Electronics',
    inStock: true,
    rating: 4.8,
    reviewsCount: 56,
    isFeatured: true,
  },
]
